### ISSUE TITLE
URL Uploads next to image

### ISSUE THREAD

**Issue by donovanwilliams** [CouchCMS/CouchCMS#108]
Hello!

Whenever I upload an image it is always accompanied by the corresponding URL (example below). I'm not sure why it's doing this.
![Screen Shot 2020-03-26 at 3 36 28 PM](https://user-images.githubusercontent.com/16489204/77694281-c1b6de80-6f77-11ea-94d3-9fa3ae4c1a29.png)

This html reads simply with the img tag and text next to it outside of tags. Any help would be appreciated.

**Comment by kksidd** [comment]
Hi,

Please see the following post from our [forum](https://www.couchcms.com/forum/viewtopic.php?f=4&t=11207#p29379).

Hope it helps.

**Comment by donovanwilliams** [comment]
Thank you!
