### ISSUE TITLE
Mutiple Templates on Single Page Website

### ISSUE THREAD

**Issue by donovanwilliams** [CouchCMS/CouchCMS#109]
Hello,

Would there be a way to create multiple templates for a single page site? The reason being, I want each section and it's editables separated by template to make the dashboard look cleaner. That way, if I add a new section I can add a new template.

I've looked through the documentation but can't seem to think of one

**Comment by genxcoders** [comment]
Yes one can easily create different templates for a single page site. The only reason to do so is to keep the admin panel (dashboard) cleaner.

This particular requirement cannot be found on documentation.

But for your ease I will define it below.

1. Consider two sections in your template, viz: 
(i) About
(ii) Gallery
2. Create templates for the two sections, let us say:
(i) about.php
(ii) gallery.php
3. Define all the editable regions in the respective template. For example: in the above template you may need a _section title_ and a _description area_ while in gallery you may need _images editables_
4. Do not forget the basics of CouchCMS, make sure you use the boiler plates for the template and then define the editable regions and finally make the compulsory visit to the template and the backend.
5. after following the above steps you will have in the admin panel (backend) the templates with the required editable regions (as per your requirement).
6. Now to display the About and Gallery editables on the front end of your single page site, enclose about and gallery as:
`<cms:pages masterpage='about.php'>
   
</cms:pages>`
and
`<cms:pages masterpage='gallery.php'>
   
</cms:pages>`

And viola you will have what you need.

Regards!

**Comment by kksidd** [comment]
To complement what @genxcoders explained -
this thread on the [forum](https://www.couchcms.com/forum/viewtopic.php?f=4&t=7119#p9516) is one of several that discuss this issue.

Hope it helps.
