### ISSUE TITLE
Adding an entry of clone-able page doesn't update unless page refreshed.

### ISSUE THREAD

**Issue by jaytheking** [CouchCMS/CouchCMS#11]
When adding an entry of a clone-able page and saving it doesnt update and show the new entry when clicking on the navigation button to show the added entries
![image](https://cloud.githubusercontent.com/assets/6914788/12158604/40452c9e-b540-11e5-83b8-7690b92ccbfa.png)
Clicking on the navigation button to view the entries doesnt update unless an explicit page refresh.
![image](https://cloud.githubusercontent.com/assets/6914788/12158617/6445ba8c-b540-11e5-8ae5-a4785d7043e6.png)

For me this not a problem but is hard to explain to a client that they need to refresh every time to avoid adding duplicates.

**Comment by kksidd** [comment]
Hi,

It seems to be a cache issue and is not the normal behavior.

Could you please try the solution suggested in the following thread of our forum and let us know if it helps? 
http://www.couchcms.com/forum/viewtopic.php?p=20383#p20383

Thanks.

**Comment by jaytheking** [comment]
This has seemed to remedy the issue. Noted though that i don't have any cache turned on in my .htaccess files either as i looked there first.
