### ISSUE TITLE
Deprecated function error got on following the tutorial steps

### ISSUE THREAD

**Issue by matheusassed** [CouchCMS/CouchCMS#110]
While following the tutorial, got this error on trying to upload an image:
![image](https://user-images.githubusercontent.com/13953825/77721837-c193fe80-6fca-11ea-9f41-4b424fe95d51.png)

Error text:
Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\xampp\htdocs\couch\couch\includes\kcfinder\lib\class_input.php on line 38

Code used to generate the field:
`
<cms:editable name='imagem_destacada'
	crop='1'
	width='610'
	height='150'
	type='image'
/>
`

Error line at the error message path:
`$this->magic_quotes_gpc = function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc();`

**Comment by matheusassed** [comment]
Disabling KCFinder, it works. But the UI is terrible.

**Comment by kksidd** [comment]
Thanks for the heads-up.

I have committed the requisite change.
Could you please test it and let me know if works?

**Comment by matheusassed** [comment]
> 
> 
> Thanks for the heads-up.
> 
> I have committed the requisite change.
> Could you please test it and let me know if works?

It works, problem solved!
Thank's @kksidd for the ultra fast update.
