### ISSUE TITLE
Single Change for Multiple Pages

### ISSUE THREAD

**Issue by donovanwilliams** [CouchCMS/CouchCMS#111]
I can't seem to figure out how to make one change for multiple php pages.

For example, if I set the page title for index.php I would like every other page to have the same title without having to manually updating each page.

It looks like a clonable page issue, but I can't seem to figure it out. Any help is appreciated.

**Comment by kksidd** [comment]
I think what you are looking for are 'global' values (i.e. shared across pages of the same template or across templates site-wide).

An older way of doing this was through the use of a separate non-clonable template (conventionally named 'globals.php') - you can find this technique being used in our [Aurelius tutorial](https://docs.couchcms.com/tutorials/portfolio-site/tying-the-loose-ends.html).

From v2.x, one can also use 'Template globals' for sharing values across pages of the same template - please see this [forum post](https://www.couchcms.com/forum/viewtopic.php?f=5&t=11105) for details.

Hope this helps. If any further help is required, I request you to please use the dedicated forum.
Thanks.
