### ISSUE TITLE
Making Blank Elements Disappear

### ISSUE THREAD

**Issue by donovanwilliams** [CouchCMS/CouchCMS#112]
Hello,

Is it possible to make elements that have no information disappear? For example, I have social media icons on a layout, but I want the ones that aren't filled with the URL to not display.

Any help is appreciated

**Comment by kksidd** [comment]
The 'Aurelius' tutorial covers this very scenario - please see [the section](https://docs.couchcms.com/tutorials/portfolio-site/contact-form.html) where social profiles are handled.

Hope it helps.
