### ISSUE TITLE
Couch Sitemap Rendering Issue

### ISSUE THREAD

**Issue by tafadzwa2015** [CouchCMS/CouchCMS#114]
Couch Sitemap (https://www.couchcms.com/forum/viewtopic.php?f=8&t=11000) not rendering

<img width="950" alt="Screenshot 2020-05-26 at 12 11 21" src="https://user-images.githubusercontent.com/13080327/82888794-14961d80-9f4a-11ea-8418-4ef9e3dbdcff.png">

**Comment by kksidd** [comment]
I request you to please post this issue in the forum thread in question. Please also attach your template along-with.
