### ISSUE TITLE
Reflected XSS vulnerability in couch/includes/plupload/upload.php

### ISSUE THREAD

**Issue by nenf** [CouchCMS/CouchCMS#126]
There is Reflected XSS vulnerability in `couch/includes/plupload/upload.php` file.

The vulnerable code is:

upload.php:9 `$fn = ( isset($_GET['fn']) ) ? $_GET['fn'] : '/';`
upload.php:12 `$upload_link = K_ADMIN_URL . 'uploader.php?tpl='.$tpl.'&fid='.$fid.'&fn='.$fn.'&nonce='. $nonce;`
upload.php:157 `url: '<?php echo $upload_link; ?>',`

Reflected cross-site scripting (or XSS) arises when an application receives data in an HTTP request and includes that data within the immediate response in an unsafe way. If an attacker can control a script that is executed in the victim's browser, then they can typically fully compromise that user.

To prevent xss use next manual: https://portswigger.net/web-security/cross-site-scripting/preventing.

Please let me know about any fixes, I would like to register CVE number.

**Comment by trendoman** [comment]
Nope. That particular application does not respond to a HTTP request.
```php
if ( !defined('K_COUCH_DIR') ) die(); // cannot be loaded directly
```
**Note:** If you don't have time to actually study the code, find another hobby ;-)
