### ISSUE TITLE
Open redirect vulnerability in couch/addons/cart/cart.php

### ISSUE THREAD

**Issue by nenf** [CouchCMS/CouchCMS#127]
Hi, dev team!

There is Open redirect vulnerability in `couch/addons/cart/cart.php` file.

The vulnerable code is:

cart.php:589: `$location = $FUNCS->sanitize_url( trim($_GET['redirect']) ); // $_GET already comes urldecoded`
cart.php:605: `header( "Location: " . $location );`

Open redirection vulnerabilities arise when an application incorporates user-controllable data into the target of a redirection in an unsafe way. An attacker can construct a URL within the application that causes a redirection to an arbitrary external domain.

To prevent Open redirect vulnerability use next manual: https://portswigger.net/kb/issues/00500100_open-redirection-reflected (`Remediation: Open redirection` section)

Please let me know about any fixes, I would like to register CVE number.

**Comment by trendoman** [comment]
@nenf Are you trying to *get some hype* or simply did not pay attention to the source code?

The very next line says &mdash;
>// we don't allow redirects external to our site
```php
// redirect specified?
if( isset($_GET['redirect']) ){
    $location = $FUNCS->sanitize_url( trim($_GET['redirect']) ); // $_GET already comes urldecoded
    if( strpos($location, K_SITE_URL)!==0 ){ // we don't allow redirects external to our site
        $location = '';
    }
}
```

P.S. Where is Mumu?

**Comment by nenf** [comment]
Sorry, you are right, didn't catch `strpos($location, K_SITE_URL)!==0 `.

**Comment by trendoman** [comment]
No probs. Wish you catch a big fish next time! 🥇
