### ISSUE TITLE
XSS via SVG file upload in CouchCMS

### ISSUE THREAD

**Issue by xxcdd** [CouchCMS/CouchCMS#130]
Affected software: CouchCMS Latest

Type of vulnerability: XSS via SVG file upload.

Description: CouchCMS is prone to a Persistent Cross-Site Scripting attack that allows a malicious user to inject HTML or scripts that can access any cookies, session tokens, or other sensitive information retained by your browser and used with that site.

Remediation: Your script should properly sanitize user input.
https://www.owasp.org/index.php/Unrestricted_File_Upload

Steps to reproduce the vulnerability:
1. login site.
2. Find the upload file URL: http://127.0.0.1/couch/includes/kcfinder/browse.php?nonce=02b16f710f786c61f34e301eae552bdf&type=file&CKEditor=f_main_content&CKEditorFuncNum=1&langCode=en
**The nonce maybe different，need to change your own**;
3. Upload SVG file with crafted XSS code:
![image](https://user-images.githubusercontent.com/42600601/105487827-acbbf080-5ceb-11eb-82ee-148ca66ecc5d.png)
4. Open uploaded the file to execute XSS payload:
URL: http://127.0.0.1/couch/uploads/file/xss.svg
![image](https://user-images.githubusercontent.com/42600601/105487990-f0165f00-5ceb-11eb-9fe2-b87130de6593.png)

xss.svg content for test:
```
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" baseProfile="full" xmlns="http://www.w3.org/2000/svg">
  <polygon id="triangle" points="0,0 0,50 50,0" fill="#009900" stroke="#004400"/>
  <script type="text/javascript">
    alert(document.cookie);
  </script>
</svg>
```

BTW: this also can cause SSRF vul, ssrf.svg content for test:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200">
<image height="200" width="200" xlink:href="http://test_ip:1234" />
</svg>
```

Repair suggestions：
1. All uploads that are suspected of being XML are checked regardless of the extension (SVG is also a kind of XML);
2. Check if there is an external entity in the XML file;
3. Check if the HTML file contains server-side include or PHP code.

**Comment by kksidd** [comment]
Hi,

Please allow me to put something in perspective -
Couch is a *single-user* CMS i.e. only (and only) a user with admin privilege is allowed to use the admin-panel.
In other words, only the site-owner (or the developer) can do so.

With that in context, what the use-case you described does is allow the site-owner to execute JS on her site *by her own volition* .

It would be a vulnerability if -
1.  somebody could cause her to inadvertantly upload this file that then executed the JS - that would be CSRF but the nonce in the URL prevents that from happening.

2.  a non-admin (or unauthenticated visitor) could upload such a file from the front-end (remember, admin-panel is off-limits to them). This is also not possible as, for front-end submissions, Couch uses a different region called 'securefile' (that, incidentally, imposes all the suggestions from owasp.org).

So, in closing, uploading SVG indeed entails the security risks you mentioned and this is why (even in WordPress) the best form of security is to allow only trusted users to upload it. This is enforced by Couch.
