### ISSUE TITLE
Full Path Disclosure by changing the parameter

### ISSUE THREAD

**Issue by Hades484** [CouchCMS/CouchCMS#132]
Application using two-parameter to pass the user action by altering the parameter itself application through the error message with the full path.
Original parameter -  a, q
By adding "[]" at the end of these parameters will lead to the full path disclosure.
![image](https://user-images.githubusercontent.com/78723738/107192808-1d654b80-6a14-11eb-9153-047bb93bbb52.png)

**Comment by kksidd** [comment]
Hi,

With regards to 'Full path disclosure', we follow [Wordpress' guidelines](https://core.trac.wordpress.org/ticket/38317#comment:1) that state it is *not* a security issue , nor is it something that intends on being "fixed" as it's not encountered during "standard usage". 

On a production server, error displays should always be [disabled ](https://www.mattcutts.com/blog/fixing-full-path-disclosure-vulnerability/) -
In a php.ini file, you can add a line like “display_errors = off” (without the quotes).
In an .htaccess file, you can add a line that says “php_flag display_errors off” (without the quotes).
