### ISSUE TITLE
Host Header Injection

### ISSUE THREAD

**Issue by Hades484** [CouchCMS/CouchCMS#133]
Host header injection vulnerability found on CouchCMS, Using this attack, a malicious user can poison the web cache or arbitrary user re-direction.
![image](https://user-images.githubusercontent.com/78723738/107202564-59061280-6a20-11eb-8abf-1eb23075b01e.png)
The same can be replicated in the burp suite.
![image](https://user-images.githubusercontent.com/78723738/107202818-a08c9e80-6a20-11eb-941e-674db4a13c37.png)

**Comment by kksidd** [comment]
I'll go with what [Microweber](https://github.com/microweber/microweber/issues/717#issuecomment-775271953) responded on this issue - it is a server configuration problem.

That said, in Couch one can explicitly define the site's canonical URL in the config file ( 'K_SITE_URL' setting ) which will completely bypass this issue regardless of the server's configuration.
