### ISSUE TITLE
cms:repeatable automatically adds a new row

### ISSUE THREAD

**Issue by sergejostir** [CouchCMS/CouchCMS#137]
Hello.

If you create a repeatable section, you can't keep it empty. Even if you delete all rows, as soon as you press "save" a new row will be created. This makes "required" attribute useless, since if any of the fields in the repeatable section is required, then you can't "save" until you delete the automatically created row every single time.

**Comment by trendoman** [comment]
That's true. If you want a quick fix --
Navigate to `couch/addons/repeatable/tablegear/tablegear.js`

Change this
```
options = options || {};
```
to - 
```
options = options || {}; options['addDefaultRow'] = '1';
```

I have used this successfully to avoid a default row.

**Comment by sergejostir** [comment]
Thanks for your input! I looked into the code then and found out that the "repeatable" tag actually has an undocumented parameter "no_default_row" with which you can control the setting that you mentioned.

https://github.com/CouchCMS/CouchCMS/blob/c199629499e48ac88cfd11c29556770d5501b0ae/couch/addons/repeatable/repeatable.php#L251

If you set tit to "1" the default row does not get added.

**Comment by trendoman** [comment]
> Thanks for your input! I looked into the code then and found out that the "repeatable" tag actually has an undocumented parameter "no_default_row" with which you can control the setting that you mentioned.

That's correct, I totally forgot that @kksidd added this parameter! 
We had a discussion after I made some tweaks to repeatable and he decided to implement a param.
