### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by sarukuku** [CouchCMS/CouchCMS#14]
When are planning to land the PHP 7 support?

**Comment by emekalites** [comment]
Hi, upgrading CouchCMS is very critical so as to support pdo classes and at most support PHP 7.0. I had to compile mysql extension and add to php.ini so as to use CouchCMS since mysql extension has been removed from PHP 7.0

**Comment by kksidd** [comment]
@emekalites, as an interim measure you can use the following patch for Couch v2.0 - 
http://www.couchcms.com/forum/viewtopic.php?p=25072#p25072

**Comment by emekalites** [comment]
okay thanks

**Comment by Mako88** [comment]
Isn't this done since e075768f?
