### ISSUE TITLE
How to get information about the current item being added?

### ISSUE THREAD

**Issue by trendoman** [CouchCMS/CouchCMS#156]
I am hooking onto this event:

https://github.com/CouchCMS/CouchCMS/blob/775a30ce8f6b19254e75be7d449378fe47529280/couch/addons/cart/cart.php#L391

Is it guaranteed that the newly added cart item appears as the last element of array $CART->items? This event lacks **$sorting_key**, so my only resort to find the item being added is the array's position, hence the question.

**Comment by kksidd** [comment]
At the point this event is raised, the added item is guaranteed to be the last item in the $CART->items array.
