### ISSUE TITLE
Multi-lang addon makes the link have a querystring already. Resulting link becomes invalid.

### ISSUE THREAD

**Issue by trendoman** [CouchCMS/CouchCMS#158]
https://github.com/CouchCMS/CouchCMS/blob/775a30ce8f6b19254e75be7d449378fe47529280/couch/addons/extended/extended-users.php#L755

**Comment by kksidd** [comment]
Noted. Thanks.

**Comment by trendoman** [comment]
Fixed with https://github.com/CouchCMS/CouchCMS/commit/49d0e2b5cf7d37cb8cf2388d2463b9de5aca77a3?

**Comment by kksidd** [comment]
Yes :)

**Comment by trendoman** [comment]
Incidentally for another project or on purpose 😆 ?
