### ISSUE TITLE
PHP 8.1.9 errors when try to install

### ISSUE THREAD

**Issue by vjandrei** [CouchCMS/CouchCMS#166]
[Mon Jan 09 13:15:46.218146 2023] [proxy_fcgi:error] [pid 21228:tid 140355102045952] [client 84.231.43.164:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: mysqli_error(): Argument #1 ($mysql) must be of type mysqli, bool given in couch/includes/mysql2i/mysql2i.class.php:139\nStack trace:\n#0 
couch/includes/mysql2i/mysql2i.class.php(139): mysqli_error()\n#1 
couch/includes/mysql2i/mysql2i.func.php(74): mysql2i::mysql_error()\n#2 
couch/header.php(315): mysql_error()\n#3
couch/index.php(7): require_once('/home/...')\n#4 {main}\n  thrown in 
couch/includes/mysql2i/mysql2i.class.php on line 139'

**Comment by kksidd** [comment]
Fixed. Thanks for the heads-up.

You'll now find PHP8 informing you categorically that the access creds you provided for MySQL were not valid for making the connection.
