### ISSUE TITLE
Time nonces are valid for

### ISSUE THREAD

**Issue by trendoman** [CouchCMS/CouchCMS#178]
https://github.com/CouchCMS/CouchCMS/blob/f587289be47b728ee6024d8c3070d9534f570fc8/couch/functions.php#L2143

I am writing a documentation page on `check_nonce` and tested the line above, which gets ~10 full hrs ("38829" on a server with GMT+0.0). Is it working as intended? 

What should be the expected valid min-max time frame for a nonce?

**Comment by trendoman** [comment]
That's something that I can not understand — substracting 1 second from the ~10 hours still gives the ~10 hours.

```php
if( $last_period ) $valid_for--;
```

> a leeway of further 12 hours when a nonce doesn't match the current 12 hours period. In your case, the total validity time would come to 10hrs + 12 hrs = 22hrs.
> 
> Hope this answers your query.

**Comment by kksidd** [comment]
That $valid_for is *not* a count of seconds; rather it is the count of 12 hours blocks.
So by subtracting 1 from this value, we are effectively moving back to the previous 12 hour block.
Does this make it clear now?

**Comment by trendoman** [comment]
Perfectly clear. Thanks!
