### ISSUE TITLE
Caching error of relation field

### ISSUE THREAD

**Issue by trendoman** [CouchCMS/CouchCMS#184]
The recent commit's (https://github.com/CouchCMS/CouchCMS/commit/f587289be47b728ee6024d8c3070d9534f570fc8) subject is on the surface again.

> Could not successfully run query: Duplicate entry '279048-18246-279048' for key 'PRIMARY'

It is very quick to recreate the problem: Edit `theme/_system/content_form.html` and add any valid id (with respect to masterpage of relation definition) to relation field —

```xml
<cms:db_persist_form
    _invalidate_cache='1'
    _token=k_cur_token
    parent_id='279048'
/>
```

How I found this? I was editing a local 'content_form' snippet and placed a line `parent_id = frm_parent_id` and noticed that with this line the relation was not saving. I placed a fixed id and got the previously fixed issue back.

Also, if the value was persisted previously, it will not be removed. I do not see an updating query in logs (I saw `/addons/relation/relation.php` and, guess, **selected** and **inserted** interchange make the field not modified)

```xml
<cms:db_persist_form
    _invalidate_cache='1'
    _token=k_cur_token
    parent_id=frm_parent_id
/>
```

Definition:

```xml
<!-- "Parent group" row -->
<cms:editable name='row04' type='row' order='444'/>

    <!-- Shows lvl1 groups -->
    <cms:editable name='parent_id' label='Belongs to:'
      type='relation'
      masterpage=k_template_name
      has='one'
      advanced_gui='1'
      group='row04'
      class='col-md-4'
      order='11'
      />
```

UPD: Same effect with disabled theme i.e. default unmodified content_form and the line placed to `<cms:persist>`  does not save the value —

```xml
<cms:config_form_view>

  <cms:persist
      parent_id=frm_parent_id
      />

</cms:config_form_view>
```

However, the fixed id does save nicely but it is not possible to remove the value, because upon save page dies with query error.

```xml
<cms:config_form_view>

  <cms:persist
      parent_id='279045'
      />

</cms:config_form_view>
```

**Comment by kksidd** [comment]
It is not the cache issue; it is actually trying to add a duplicate record where one already exists.

I think you are trying to use explicit values with the GUI field also present on the form (which is where you'd be removing the value from). This is messing up the field's logic and it fails to remove the existing record and goes ahead with trying to add it again (and fails).

I'd suggest you either use the programmatic way or the GUI alone and not mix them.
If this is not feasible, first check if the field is not already related to the ID you are trying to add before specifying it in code.

**Comment by kksidd** [comment]
Could you please let mek now the use-case?
Also, please get (email) me the full code that I can use on my system to duplicate the issue.

**Comment by trendoman** [comment]
> Could you please let me know the exact use-case? 

I want to understand under which circumstances I need to use 'second saving' method to update persisted relation to some other value (or even nullify it) OR I need to disallow the saving completely via fencing db_persist_form.

**Comment by trendoman** [comment]
Sent an example to email.

**Comment by kksidd** [comment]
Thanks. I tested and, as I presumed, the cause is that the field's GUI present on the form sets some values based on the selection (e.g. items inserted, items deleted) and then when you set a selection programatically after this, the previously calculated values get overwritten and are no longer correct. 

This can lead to inconsistent state so the two should definitely not be used together in a single save.

If the two absolutely have to be used together, then the solution would be to use the 'second saving' method that you have been investigating e.g. following should work (the first save uses the GUI field and then the second save modifies it programatically) -

```
<cms:db_persist_form
        _invalidate_cache='1'
        _token=k_cur_token
    />

    <cms:if k_success >
        <!-- find page and edit it again -->
        <cms:set my_page_id = "<cms:if k_cur_form_mode eq 'create'><cms:show k_last_insert_id /><cms:else /><cms:show k_page_id /></cms:if>" />

        <cms:pages masterpage=k_template_name id=my_page_id show_future_entries='1' limit='1'>
            <cms:db_persist
                _masterpage=k_template_name
                _mode='edit'
                _page_id=k_page_id

                parent_id = "<cms:pages limit='1' orderby='random' ids_only='1' />"
            />
        </cms:pages>
        
        <cms:if k_redirect_link >
            <cms:set_flash name='submit_success' value='1' />
            <cms:redirect k_redirect_link />
        </cms:if>
    </cms:if>
</cms:if>
```

Hope this helps.
