### ISSUE TITLE
CSRF in CouchCMS v2.3

### ISSUE THREAD

**Issue by Fjowel** [CouchCMS/CouchCMS#189]
There is a CSRF vulnerability in CouchCMS v2.3，
check details in https://github.com/Fjowel/CSRF-vulnerability-in-CouchCMS-v2.3

**Comment by kksidd** [comment]
No, it's not.
Take a look at the URL being posted to and you'll find that it contains a value of 32 seemingly random numbers - that is a 'nonce' (or 'only once'). This is placed for avoiding CSRF and is specific to a partcular user, a particular action and a particuar time-period.

Someone trying to use a CSRF attack on a user would first need to figure out that nonce (which is impossible).
