### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by trendoman** [CouchCMS/CouchCMS#191]
https://github.com/CouchCMS/CouchCMS/blob/82bad335e4f9702f0f7aafe3f7799f7eaac396bb/couch/page.php#L339C36-L339C36

An oversight or a conscious decision? Is there a way to override this without changing the core **page.php**?

**Comment by kksidd** [comment]
TBH, I can't remember.. originally must have had a reason to use it without translation but can't seem to locate one now :)
Should be rectified.

As for overriding without changes to the core - there are multiple hooks (or even &lt;cms:config_form_view&gt; if it is a one-off change).

**Comment by trendoman** [comment]
Thanks, a hook will be used temporarily for the site-wide change. In a rare (nowadays) request I received there is a need for an updated RU.php translations. I wish CouchCMS was known in russian-speaking countries around the world, that would have helped the fix spotted earlier 💯

**Comment by trendoman** [comment]
Interestingly, addon Copy-to-New has this sorted out as follows (via `status`):

![image](https://github.com/CouchCMS/CouchCMS/assets/6024107/cd76f9a6-9ceb-4769-b5e5-1125327f3f2a)

**Comment by trendoman** [comment]
It's been a while since I last coded, so not sure if there is a more efficient hook or way to find the requried system field??

```php
<?php
    if( !defined('K_ADMIN') ) return;

    //-
    //-
    //- @author AntS <tony.smirnov@gmail.com>
    //- @date   09.09.2023
    //-

    if( K_ADMIN_LANG ){
        // HOOK: alter_system_fields_info
        $FUNCS->add_event_listener( 'alter_system_fields_info', function(&$arr_sys_fields, $pg) use ($FUNCS){

              foreach( $arr_sys_fields as $f ){
                  if( $f->name === 'k_publish_date' ){ $f->label = $FUNCS->t('publish_date'); }
              }
        });
    }
```

**Comment by trendoman** [comment]
It makes sense to also localize missing items from the system theme, e.g. Dump and htaccess, do you think so?

```xml
<a href="<cms:show k_admin_link />gen_dump.php"><cms:localize 'download_dump' /></a>
```

**Comment by kksidd** [comment]
I would prefer using the following hook -

```php
$FUNCS->add_event_listener( 'alter_pages_form_default_fields_final', function(&$arr_default_fields, &$pg) use($FUNCS){
    if( array_key_exists('k_publish_date', $arr_default_fields) && $arr_default_fields['k_publish_date']['label']=='Publish Date' ){
        $arr_default_fields['k_publish_date']['label'] = $FUNCS->t('publish_date');
    }
});
```

**Comment by trendoman** [comment]
> I would prefer using the following hook

Agree, this one is more efficient. 

Here is my new 'thank you' contribution: `form_field_deleted.html` has the unlocalized `or` which looks funny in between localized phrases.
