### ISSUE TITLE
Official respository / active development?

### ISSUE THREAD

**Issue by 4Digits** [CouchCMS/CouchCMS#2]
Is this the official repository of CouchCMS (http://www.couchcms.com/) or just a fork?

On http://www.couchcms.com/ I have seen that the latest version is 1.4, 15th Oct. 2013, which is quiet some time ago now. 

Is CouchCMS still being actively developed?

**Comment by kksidd** [comment]
Hi,

This indeed is the official repository.

As for whether Couch is being actively developed - yes, it certainly is.
Please see our forums -
http://www.couchcms.com/forum/viewtopic.php?f=5&t=8581
http://www.couchcms.com/forum/viewtopic.php?f=5&t=8981

**Comment by 4Digits** [comment]
Thanks for your quick response. Just found CouchCMS and it looks like a very interesting alternative to WordPress for small, custom sites, especially for non-technical clients.

Is there an official date for the next major release? 

Or is 1.4.5 the current stable version (opposed to 1.4 on the official website) ?

**Comment by kksidd** [comment]
Work is in progress for the next major release. Cannot commit to a fixed date, though.

In the meanwhile, you can safely use the 1.4.5 branch in production.

**Comment by 4Digits** [comment]
Great. Thanks.

**Comment by Schmidtwar** [comment]
CouchCMS it's a really great CMS, have used it for now maybe 4 month or something. Really good! And the newest update was great.
