### ISSUE TITLE
Niceedit dose not work properly with popup editing

### ISSUE THREAD

**Issue by pau-ker** [CouchCMS/CouchCMS#20]
- Couch version 2.0
![couch-niceedit-issue](https://cloud.githubusercontent.com/assets/20379982/20186251/8ba6c57c-a76f-11e6-95ba-50d60a8be186.jpg)

**Comment by cheesypoof** [comment]
Thanks for the report @pau-ker . Could you please test the referenced commit?

**Comment by pau-ker** [comment]
@cheesypoof It works. Thank you! :)
