### ISSUE TITLE
Could not successfully run query: Table 'couch_sub_templates' already exists

### ISSUE THREAD

**Issue by Aditi-Fyers** [CouchCMS/CouchCMS#208]
While upgrading from v2.2.1 to v2.4 I am facing thi sissue, I followed the steps mentioned in the forum for upgradation. Kindly help

**Comment by kksidd** [comment]
I think the upgrade process abended midway leading to this problem.

Anyway, I suggest you please do the following -
edit 'couch/upgrade.php' and comment out (i.e. place within /*  and  */ ) or even delete the code from lines 290 to 306 (i.e. everything between 
_// upgrade to 2.4_
and
_// Finally update version number_

Please try and let me know if this helps.

**Comment by Aditi-Fyers** [comment]
@kksidd Thank you, This helped fix the issue I was facing.
