### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jkathir** [CouchCMS/CouchCMS#32]
1. Google like search engine like https://ambar.cloud/
2. Next, Previous, Go to Option like Folio Views
3. Number of hits found before hitting the actual search like Folio Views
4. Import options from Zim, Treepad or other wikis.
5. Handling huge number of documents by providing quick search via Solr or Apache Lucene
6. Support for tamil language
7. Having tags for each document (Reference: https://collatenotes.com/)
8. Built in web clipper (save webpages locally) - (Reference: https://collatenotes.com/)
9. Support for full text search in huge text nodes - example atleast 10,000 nodes with 100 kb of text each. Most note-taking software couldn't handle such huge content due to missing indexing
10. Quickest search results via indexing through Apache Lucene like docFetcher (http://www.techrepublic.com/blog/linux-and-open-source/portable-desktop-search-make-the-most-of-docfetcher/)

**Comment by cheesypoof** [comment]
That's a big list @jkathir 🙂 Please post feature requests to https://www.couchcms.com/forum/viewforum.php?f=3. Thanks!
