### ISSUE TITLE
Code snippets in tutorials are actually images? What???

### ISSUE THREAD

**Issue by MB34** [CouchCMS/CouchCMS#42]
Why do you not post actual TEXT of the source instead of stupid images?
In this image , the source is clipped:
http://docs.couchcms.com/assets/img/contents/portfolio-site-184.png

Please change all your code "snippets" in your tutorials to actual source code, vs. images due to this problem.

**Comment by kksidd** [comment]
Almost every section of the tutorial has the full source code available for download (top-right corner).

The images you mentioned are meant to graphically point out what has changed in the code as the narrative in the tutorial advances - this makes it easier to see what is going on by immediately comparing with the images that precede.

In what they are supposed to do, I think they serve their purpose and are hardly 'stupid'.

**Comment by MB34** [comment]
The source that us available for download DOES NOT have the CouchCMS markup in it. And, yes, it is stupid to use an image and have it CLIPPED so you cannot see the ENTURE code snippet

**Comment by kksidd** [comment]
> The source that us available for download DOES NOT have the CouchCMS markup in it.
It actually does. Check it for yourself -
The image you quoted is found on http://docs.couchcms.com/tutorials/portfolio-site/home-page.html. The top-right corner of that page has a 'Download source code' icon. which will get you 'home.zip'.

Extract the 'index.php' template from it and you can find the code shown in the image at line 77.

> And, yes, it is stupid to use an image and have it CLIPPED so you cannot see the ENTURE code snippet
I think we should end this thread at this point as it will not yield anything worthwhile.
