### ISSUE TITLE
phpmailer.php and mysql2i.func.php disclosure the full path

### ISSUE THREAD

**Issue by ponyma233** [CouchCMS/CouchCMS#46]
Location:
`includes/mysql2i/mysql2i.func.php` and `addons/phpmailer/phpmailer.php`

Rows : 10

Harm:
Web Site physical path leakage .

![1111](https://user-images.githubusercontent.com/37031590/36942788-567b82a0-1fb6-11e8-912c-c61892afd4aa.png)
![2222](https://user-images.githubusercontent.com/37031590/36942789-56afb5ac-1fb6-11e8-86f1-06c0d98183dd.png)

**Comment by kksidd** [comment]
Fixed. Thanks for the heads-up.
