### ISSUE TITLE
Tags are appended when editing page

### ISSUE THREAD

**Issue by ayushbits** [CouchCMS/CouchCMS#52]
Hi,
I have surrounded editable content with the required tags as instructed. It appears fine in the CMS editor as well. However, when I add a content in editable box and `Save` the page, tags are inserted in the saved page.
For example,
```<cms:editable name='main_content' type='richtext'> 
<h1-mod class="blue-text line-height1.8">Heading 1</h1-mod>
<ol >
 <li> <p4-mod class="medium-font blue-text">Bullet 1</p4-mod> </p4-mod></li>
 <li> <p4-mod class="medium-font blue-text">Bullet 2</p4-mod> </p4-mod></li>
 <li> <p4-mod class="medium-font blue-text">Bullet 3</p4-mod> </p4-mod></li>
</ol> 
```
The content appears fine in CMS editor initially, but when I make any changes to the content, the output page contains tags as well and original fonts are also changed.
Please guide how to solve this issue.

Regards,
Ayush

**Comment by kksidd** [comment]
Hi Ayush,

Could you please post this issue on our forums? [https://www.couchcms.com/forum/index.php](url)
We'd be able to help you better that way.

Also please post some screenshots of exactly what you see happening.

Thanks,
