### ISSUE TITLE
Cloudflare Rocket Loader breaking Admin panel Ckeditor editor

### ISSUE THREAD

**Issue by NinoSkopac** [CouchCMS/CouchCMS#7]
Took me about 7 hours to figure out what the issue was (I was migrating site) on latest Couch build.

Related: 
http://www.couchcms.com/forum/viewtopic.php?f=4&t=8699
https://support.cloudflare.com/hc/en-us/articles/200169976-Why-isn-t-my-CMS-editor-working-after-changing-to-CloudFlare-

Buggy interface:
![capture](https://cloud.githubusercontent.com/assets/1783732/8715403/b7f47d06-2b81-11e5-85f8-3bea9bdfbd87.JPG)

You can turn off Rocket loader globally, but I did the following to fix the problem:
In admin\includes\ckeditor\ckeditor_php5.php:460, I replaced with the following:

```php
$out .= "<script type=\"text/javascript\" data-cfasync=\"false\" src=\"" . $ckeditorPath . 'ckeditor.js' . $args . "\"></script>\n";
```

I realize this is a addon issue, but still, might be helpful to fix.

**Comment by cheesypoof** [comment]
Rocket Loader is considered a beta feature. I have encountered a similar issue before and it also took me some time to troubleshoot.

Compatibility of the admin panel might be investigated, but it is not a priority item. I don't think we would want to adopt such a service-specific solution, as I am sure there are others out there providing similar functionality (which have the side effect of breaking the admin panel).

You need not disable Rocket Loader globally or create page rules, if this does benefit your front-end loading. Why not change the setting from Automatic (opt-out) to Manual (opt-in)? Add `data-cfasync="true"` to your front-end scripts and you won't need to modify core Couch files.
