### ISSUE TITLE
Security issue in function cleanXSS

### ISSUE THREAD

**Issue by asafrubin** [CouchCMS/CouchCMS#95]
it is possible to bypass the cleanXSS function (in [https://github.com/CouchCMS/CouchCMS/blob/master/couch/functions.php](functions.php)) and anyone who have control on the input to the function can inject code that can cause XSS.
so any piece of code which relies on cleanXSS to filter the input from XSS may be vulnerable to either reflected XSS or stored XSS - depends on the situation.
(some other attacks might be possible).

this is the code i used to test the cleanXSS function (i didn't revealed here the payload string for obvious reasons) (sorry for the bad php :) ) :
````
<?php
ob_start();

if ( !defined('K_COUCH_DIR') ) define( 'K_COUCH_DIR', str_replace( '\\', '/', dirname(realpath(__FILE__) ).'/') );
$get = isset( $_GET['redirect'] ) ? $_GET['redirect'] : null; // get it before header.php sanitizes and converts '&' to '&amp;';
require_once( K_COUCH_DIR.'header.php' );
$_GET['redirect'] = $get; // can bypass sanitization because we'll sanitize URL ourselves later on.

$default_dest = ( $AUTH->user->access_level < K_ACCESS_LEVEL_ADMIN ) ? K_SITE_URL : K_ADMIN_URL . K_ADMIN_PAGE;
$dest = isset($_GET['redirect']) ? $_GET['redirect'] : $default_dest;


global $FUNCS;

$result = new KFuncs();
$text = $_GET['input'];
$check = strlen ($text);
//$text = trim( $text );
$check = strlen ($text);
$text = $FUNCS->cleanXSS($_GET['input']);

echo "<!DOCTYPE html>\r\n";
echo $text . "\r\n" ;
````

and here is the generated page:

![vuln](https://user-images.githubusercontent.com/28262537/56080542-f4210780-5e0a-11e9-816b-9e41f7a37b22.jpg)

**Comment by kksidd** [comment]
Hi,

I'd like to check the issue with the payload you used.
Could you please contact me directly at kksidd@couchcms.com and get me the payload?

Thanks

**Comment by asafrubin** [comment]
> Hi,
> 
> I'd like to check the issue with the payload you used.
> Could you please contact me directly at [kksidd@couchcms.com](mailto:kksidd@couchcms.com) and get me the payload?
> 
> Thanks

of course, no problem.

**Comment by kksidd** [comment]
Thanks Asaf.

I have made the necessary changes and pushed out a security release [https://www.couchcms.com/forum/viewtopic.php?f=5&t=12147](url)
