### ISSUE TITLE
Groups in cloneable pages

### ISSUE THREAD

**Issue by SimonWpt** [CouchCMS/CouchCMS#98]
When I rename a group in cloneable pages, the old named group will not be deleted. The old group is not deletable in any manner.

**Comment by kksidd** [comment]
Sorry but I was unable to recreate this issue in my tests.
Perhaps it has something to do specifically with how you have coded things?

I request you to please post your code at [our forums](https://www.couchcms.com/forum/index.php) and I'll be happy to test it out.
