### ISSUE TITLE
thumbnail stops working

### ISSUE THREAD

**Issue by SimonWpt** [CouchCMS/CouchCMS#99]
When I put some `<cms:editable type='image' />` with `<cms:editable type='thumbnail' />` in a row, `thumbnail` stops after rendering 1-2 photos. And I don't understand, why thumbnails are shown after all images in Backend.

![Screenshot](https://user-images.githubusercontent.com/160817/65700997-dfff5880-e080-11e9-91d1-b9326602d526.png)
Used PNG: http://placehold.jp/99ccff/003366/1280x1160.png

``` 
<cms:editable name='g4' label='Gallery 4' type='group' collapsed='0'/>
<cms:editable type='image' name='foto41' label='Photo' group='g4' show_preview='1' preview_width='150' desc='Photo 1'/>
<cms:editable type='thumbnail' name='foto41thumb' label='Photo Ausschnitt' group='g4' show_preview='1' preview_width='150' width='640' height='580' quality='90' assoc_field='foto41'/>
<cms:editable type='image' name='foto42' label='Photo' group='g4' show_preview='1' preview_width='150' desc='Photo 2'/>
<cms:editable type='thumbnail' name='foto42thumb' label='Photo Ausschnitt' group='g4' show_preview='1' preview_width='150' width='640' height='580' quality='90' assoc_field='foto42'/>
<cms:editable type='image' name='foto43' label='Photo' group='g4' show_preview='1' preview_width='150' desc='Photo 3'/>
<cms:editable type='thumbnail' name='foto43thumb' label='Photo Ausschnitt' group='g4' show_preview='1' preview_width='150' width='640' height='580' quality='90' assoc_field='foto43'/>
<cms:editable type='image' name='foto44' label='Photo' group='g4' show_preview='1' preview_width='150' desc='Photo 4'/>
<cms:editable type='thumbnail' name='foto44thumb' label='Photo Ausschnitt' group='g4' show_preview='1' preview_width='150' width='640' height='580' quality='90' assoc_field='foto44'/>
```

**Comment by kksidd** [comment]
Appears to be an 'insufficient memory' problem to me.
Please visit our forum and you'll find several discussions on solving this issue.

As for the other point you made (all thumbnails appearing after the image regions), one possible explanation is that you added these thumbnail regions **after** the image regions were already added (the default sorting order is the creation time).

Please try explicitly adding the 'order' parameter with all regions to tweak their ordering.
Again, please visit our forum if you are unclear about this.
